### ISSUE TITLE
Types have separate declarations of a private property 'clientId'.

### ISSUE THREAD

**Issue by do4Mother** [bizon/selling-partner-api-sdk#1053]
i get this error in my project.
`Types have separate declarations of a private property 'clientId'.`

i have already installed for orders, catalog and listing api from `@sp-api-sdk` everything is working fine. but except with `listings restrictions` package.

i use same package version of authentication. which is version 2.0.2

<img width="561" alt="Screenshot 2023-11-22 at 09 49 47" src="https://github.com/bizon/selling-partner-api-sdk/assets/24775044/7792f362-a1fb-4189-b0d6-b09de7eb16c9">

**Comment by do4Mother** [comment]
resolved by removing the node_modules package and the yarn.lock file and attempting to reinstall the package.

**Comment by tusbar** [comment]
This happens when you have different versions of `@sp-api-sdk/auth` – run `yarn why @sp-api-sdk/auth` to view them.

Can be fixed by installing the lastest version of each package.
