### ISSUE TITLE
(Bug) Invalid input content type

### ISSUE THREAD

**Issue by PixsaOJ** [bizon/selling-partner-api-sdk#1178]
I am trying to cancel fulfillment order using `cancelFulfillmentOrder`

I saw this issue on version `1.10.3` so I upgraded to `2.1.1` and upgraded Auth library as well.

For some reason I get this content type error. Is it possible that Amazon has new requirement for content type? Maybe `charset=utf8` is not set. I don't recall having this issue before.

```bash
[
  {
    code: 'InvalidInput',
    message: 'Invalid Input',
    details: 'Content type must be set to application/json; charset=utf-8.'
  }
]
```

How I use it
```Javascript
await this.client.cancelFulfillmentOrder({
  sellerFulfillmentOrderId: id
})
.then((response) => {})
```

**Comment by tusbar** [comment]
Hello @PixsaOJ, 

It seems like an issue with the models over on https://github.com/amzn/selling-partner-api-models.

You could work around this issue by using the [2nd parameter](https://bizon.github.io/selling-partner-api-sdk/classes/_sp_api_sdk_fulfillment_outbound_api_2020_07_01.FulfillmentOutboundApiClient.html#cancelFulfillmentOrder).

```ts
await this.client.cancelFulfillmentOrder({
  sellerFulfillmentOrderId: id
}, {
  headers: {
    'content-type': 'application/json'
  }
})
```

Let me know if it fixes the issue for you.

**Comment by PixsaOJ** [comment]
Hi, I believe i was passing `null` as `id`. The error was misleading, because it has nothing to do with content type.

**Comment by PixsaOJ** [comment]
I'm reopening issue, id is not `null`  and I still get code 400 with same error message. I'm tired of this.

**Comment by tusbar** [comment]
@PixsaOJ this is probably an issue with the models from Amazon
