### ISSUE TITLE
[feature request] expose SellingPartnerApiAuth accessTokenExpiration

### ISSUE THREAD

**Issue by michael-land** [bizon/selling-partner-api-sdk#1373]
My use case involves running some functions in a serverless environment, where we would like to cache the access token.

It would be helpful if the API could expose the expiration time, either through a function or by making the variable `protected readonly` instead of `private readonly`. This way, I wouldn’t need to use a workaround like 3600-60.

I'm happy to create a PR if you don’t have time to implement this.

```ts
class SellingPartnerApiAuthCloudflare extends SellingPartnerApiAuth {
  private readonly kv: KVNamespace;
  private readonly identifier: string;
  constructor({
    kv,
    clientId,
    clientSecret,
    refreshToken,
  }: {
    kv: KVNamespace;
    clientId: string;
    clientSecret: string;
    refreshToken: string;
  }) {
    super({ clientId, clientSecret, refreshToken });
    this.identifier = refreshToken;
    this.kv = kv;
  }
  override async getAccessToken() {
    let token = await this.kv.get(this.identifier);

    if (!token) {
      console.log('Token not found in KV');
      token = await super.getAccessToken();
      await this.kv.put(this.identifier, token, { expirationTtl: 3600 - 60 });
    } else {
      console.log('Token found in KV');
    }

    return token;
  }
}
```

**Comment by tusbar** [comment]
Hello @michael-land – so I understand better, you want to reuse the same access token across multiple serverless invocations?

`SellingPartnerApiAuth#getAccessToken` already caches an access token in memory (and handles renewal).

**Comment by tusbar** [comment]
@michael-land you’ll be able to use `this.accessTokenExpiration` – which is a readonly protected property, once #1377 is released.

**Comment by tusbar** [comment]
https://bizon.github.io/selling-partner-api-sdk/modules/_sp-api-sdk_auth.html#subclassing should be good for your use case.
