### ISSUE TITLE
Getting error code 429: "QuotaExceeded"

### ISSUE THREAD

**Issue by froyoga** [bizon/selling-partner-api-sdk#534]
I have an array of orders that I loop through to get order items for each of them, using `getOrderItems()`. I've set `retry: true` it'll work for a few retries. Sometimes I'm able to loop though the entire array, but other times I'll get a 429 response. Is there anything I can do for it to keep retrying until it completes the loop?

**Comment by tusbar** [comment]
Hey @froyoga 

`axios-retry` is actually configured to retry only 3 times (default value), we may allow for more retries, but it is often not the best strategy when iterating over a large array: each request will be retried independently, hence not respecting the global rate limits.

I’d suggest using a package like [`p-throttle`](https://github.com/sindresorhus/p-throttle) to limit the concurrent calls.

You could do something like this:

```ts
import {OrdersApiClient} from '@sp-api-sdk/orders-api-v0'
import pThrottle from 'p-throttle'

// getOrderItems refills 0.5 req per second
// https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-reference#get-ordersv0ordersorderidorderitems
const throttle = pThrottle({
  limit: 1,
  interval: 2000,
})

const client = new OrdersApiClient({/* … */})
const getOrderItems = throttle(getOrderItems.bind(client))

await Promise.all(yourLargeArrayOfOrders.map(async order => {
  let nextToken: string | undefined

  do {
    const {data} = await getOrderItems({
      orderId: order.orderId,
      nextToken
    })

    // …
  } while (nextToken)
}))
```

Keep in mind that p-throttle does consider the size of the bucket (which is 30 for this API call).
We may implement something like this in here in the future, no plans yet. :)

**Comment by froyoga** [comment]
Thanks. I ended up using [exponential-backoff](https://github.com/coveooss/exponential-backoff) and it's been working for me thus far.
