### ISSUE TITLE
Error using "na" region.

### ISSUE THREAD

**Issue by jircdev** [bizon/selling-partner-api-sdk#710]
Hi, first of all, I'd like to thank you for your help.

I'm attempting to configure the selling-partner-api-sdk to retrieve the inventory information from my Amazon seller partner account, but I am encountering an error "region is missing" from the "@aws-sdk" package. I have already defined the region in the instance of "FbaInventoryApiClient." I'm not sure if this is an error or just a bad implementation,

This is my code (All values in upper are constants):  
```
        const auth = new SellingPartnerApiAuth({
            clientId: CLIENT_ID,
            clientSecret: ACCESS_SECRET_KEY,
            refreshToken: REFRESH_TOKEN,
            accessKeyId: ACCESS_KEY_ID,
            secretAccessKey: ACCESS_SECRET_KEY,
            role: {
                arn: ARN,
            },
        });

        const client = new FbaInventoryApiClient({
            auth,
            region: "na", // as the ts docs says.
        });

        const specs = {
            granularityType: "Marketplace",
            granularityId: MARKETPLACE_ID,
            marketplaceIds: [MARKETPLACE_ID],
        };


        client.getInventorySummaries(specs);
 ```
I got the next error: 
![image](https://user-images.githubusercontent.com/7352361/218451043-1c3a6b99-2768-4969-bff7-2c8e1659ac5d.png)

Trying to debug, I found that the "_sts_ property of the  SellingPartnerApiAuth has an undefined value in region property as you can see in the following image: 
![image](https://user-images.githubusercontent.com/7352361/218450178-623f779b-b7f9-4fb8-a08a-65df89f638f2.png)

Thanks for your answer

**Comment by tusbar** [comment]
Hey,

You need to specify an AWS region to the `SellingPartnerApiAuth` for the STS calls: 

```diff
 const auth = new SellingPartnerApiAuth({
    clientId: CLIENT_ID,
    clientSecret: ACCESS_SECRET_KEY,
    refreshToken: REFRESH_TOKEN,
    accessKeyId: ACCESS_KEY_ID,
    secretAccessKey: ACCESS_SECRET_KEY,
+   region: 'us‑west‑1', // Or your preferred AWS region
    role: {
        arn: ARN,
    },
});

```

**Comment by jircdev** [comment]
Thank you. I was following the example in docs and how I saw it in the FbaInventoryApiClient, I thought was ok.

I have another doubt. I am not sure if you can answer me in this threat.

Wich is the role arn we need to put in SellingPartnetApiAuth instance to correctly access to the api? I put the IAM user and the ARN executing API ARN and the IAM role but with both I had errors.

**Comment by jircdev** [comment]
Thank you. I followed the example in the docs and thought everything was okay since I saw it in the FbaInventoryApiClient.

I have another doubt, and I'm not sure if you can answer it in this thread. I will ask, and please let me know if I need to close the ticket. Thank you for your patience.

I am receiving a 401 error with the message "SellingPartnerApiAuthError: access-token error: Response code 401."

I'm not sure what the correct way to proceed is. I understood that I need to set the "accessToken". While checking out the parameters of SellingPartnerAuth, I saw the "sessionToken." Is it the same? If not, what is the correct way to generate the access token using the package? Can I get the access token using some method?

Thank you very much for your help.

**Comment by tusbar** [comment]
@jircdev something must be wrong with your configuration values. I’m thinking maybe `ACCESS_SECRET_KEY` that is both used for `clientSecret and `secretAccessKey`.

`clientId` and `clientSecret` are LWA credentials.  
`accessKeyId` and `secretAccessKey` are AWS credentials.

https://github.com/bizon/selling-partner-api-sdk/tree/master/packages/auth should have all the info you need.

**Comment by jircdev** [comment]
Thank you for your response. I appreciate your feedback. Another developer has informed me that it may not be possible to directly access inventory data and that working with reports may be necessary. I had attempted to use the Amazon inventory API to retrieve the available quantity of specific SKUs. However, if it is indeed not possible to access the data directly, I will need to implement a cron job instead of using this package. Could you please confirm if this is the correct approach? Thank you once again for your help.
