### ISSUE TITLE
Feature request: Export the Api classses

### ISSUE THREAD

**Issue by florianbepunkt** [bizon/selling-partner-api-sdk#757]
In the generated clients, would it be possible to export the api classes as well?

https://github.com/bizon/selling-partner-api-sdk/blob/43fb1418024a0ad214440263946a5c78e2d52728/clients/sellers-api-v1/src/client.ts#L15

Currently only `SellersApiClient ` is exported, but not `SellersApi `. I need to use a custom axios instance and the cleanest way would be to subclass SellersApi (or any other model) and pass my own axios instance.

**Comment by tusbar** [comment]
@florianbepunkt better late than never, this is now possible.
