### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by Philomath88** [bizon/selling-partner-api-sdk#781]
I am trying to use npm install but I get the following error: 

npm ERR!     /Users/maximiliandoelle/.npm/_logs/2023-04-19T05_17_35_086Z-debug-0.log
(base) maximiliandoelle@Maximilians-MBP selling % npm install @sp-api-sdk/catalog-items-api-2022-04-01
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @sp-api-sdk/catalog-items-api-2022-04-01@1.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maximiliandoelle/.npm/_logs/2023-04-19T05_18_11_629Z-debug-0.log
(base) maximiliandoelle@Maximilians-MBP selling % npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @sp-api-sdk/catalog-items-api-2022-04-01@1.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/maximiliandoelle/.npm/_logs/2023-04-19T05_18_17_158Z-debug-0.log
(base) maximiliandoelle@Maximilians-MBP selling % yarn install
zsh: command not found: yarn

Am also looking for a freelancer to help a noob like me :) If you are interested, drop me a line at maxdoelle(at)gmail.com

**Comment by tusbar** [comment]
You’re trying to install version `1.0.0` of the `@sp-api-sdk/catalog-items-api-2022-04-01` package, which does not exist.

Try installing the latest version:  
https://www.npmjs.com/package/@sp-api-sdk/catalog-items-api-2022-04-01?activeTab=versions
