### ISSUE TITLE
Requesting vendorDetails in getCatalogItem results in 400 response error

### ISSUE THREAD

**Issue by froyoga** [bizon/selling-partner-api-sdk#819]
When using `catalog-items-api-2022-04-01`...

This works:
```
await client.getCatalogItem({
    asin,
    marketplaceIds: [marketplace.marketplaceId],
});
```

This also works:
```
await client.getCatalogItem({
    asin,
    marketplaceIds: [marketplace.marketplaceId],
    includedData: ["summaries"],
});
```

However, this results in a 400:
```
await client.getCatalogItem({
    asin,
    marketplaceIds: [marketplace.marketplaceId],
    includedData: ["summaries", "vendorDetails"],
});
```

Is this because "Vendor details are available to vendors only"? If so, how do I specify myself as a vendor when making this request? Thanks.

**Comment by tusbar** [comment]
`vendorDetails` is only available to Amazon Vendor accounts (Retail), you’re using the API for an Amazon Seller account (Marketplace), hence the error message.
