### ISSUE TITLE
[Bug] omit sessionToken if undefined

### ISSUE THREAD

**Issue by michael-land** [bizon/selling-partner-api-sdk#881]
For self-authorized sellers who obtain an access token using a refresh token, when attempting to assume roles with SST, an undefined sessionToken results in an InvalidClientTokenId error. It seems that the undefined value is being converted to the string 'undefined'..

```ts
    const auth = new SellingPartnerApiAuth({
      clientId: '',
      clientSecret: '',
      accessKeyId: '',
      secretAccessKey: '',
      refreshToken: 'Atzr|',
      role: { arn: '' },
    });

    const client = new OrdersApiClient({
      auth,
      region: 'na',
    });

    const {
      data: { payload },
    } = await client.getOrders({
      marketplaceIds: ['ATVPDKIKX0DER'],
      createdAfter: new Date('2022-01-01').toISOString(),
    });
    console.log(payload?.Orders.length);

```
|  +1648ms InvalidClientTokenId: The security token included in the request is invalid
|  +1648ms     at throwDefaultError (/Users/.../node_modules/.pnpm/@smithy+smithy-client@1.0.3/node_modules/@smithy/smithy-client/dist-es/default-error-handler.js:5:22)

The issue was resolved by commenting out the sessionToken parameter in the "@sp-api-sdk/auth/sts" module. This modification allowed the functionality to work correctly.

<img width="814" alt="CleanShot 2023-07-05 at 14 52 30@2x" src="https://github.com/bizon/selling-partner-api-sdk/assets/33362998/23392493-c62c-4be1-8f3f-f95e7d130f30">

<img width="648" alt="CleanShot 2023-07-05 at 14 57 52@2x" src="https://github.com/bizon/selling-partner-api-sdk/assets/33362998/dbd35bca-16a5-4d68-a8f9-09fbe1653f4f">

**Comment by michael-land** [comment]
<img width="775" alt="CleanShot 2023-07-05 at 14 59 14@2x" src="https://github.com/bizon/selling-partner-api-sdk/assets/33362998/86e49360-e3d9-46fa-8a29-e021552770b8">

I suggest that it can be changed like this.

**Comment by tusbar** [comment]
Hello,

This doesn’t make sense, if `this.sessionToken` is `undefined`, `config.credentials.sessionToken` will be set to `undefined`.
Your suggestion will just prevent the key from being set to undefined – which should not matter.

Is it an issue with `@aws-sdk/client-sts`?

**Comment by XDapps** [comment]
Hello, I am having this same issue when deploying to AWS Lambda using a serverless config file. I am not an expert in how these things work under the hood, but I am available to test any proposed solutions that anyone may come up with.

**Comment by tusbar** [comment]
@XDapps a lambda function is always invoked using temporary credentials, by assuming the lambda’s execution role. So these environment variables are always defined:

- `AWS_SECRET_ACCESS_KEY`
- `AWS_ACCESS_KEY_ID`
- `AWS_SESSION_TOKEN`

If you’re passing different values for `accessKeyId` and `secretAccessKey`, the `AWS_SESSION_TOKEN` will be passed as well, and will cause the AWS auth to fail.

When using AWS Lambda, it’s better to allow the lambda’s execution role to `sts:AssumeRole` your SP-API Role, and not pass custom AWS credentials.

For example, if using the `serverless` framework:

```yml
  iam:
    role:
      statements:
        # Allow assuming Selling Partner IAM Role
        - Effect: Allow
          Action: [sts:AssumeRole]
          Resource: arn:aws:iam:…
```

And stop passing `accessKeyId` and `secretAccessKey` to `SellingPartnerApiAuth`.

**Comment by XDapps** [comment]
Thank you so much for the response!

The problem is, the Lambda function will have the credentials passed into it as a parameter. The function will serve multiple different sellers/stores so the credentials/role will change for each request.

I'm trying to figure out the best way to manage that.

Imagine a public app that has 100 sellers/stores. That app has 100 sets of API credentials.

Now a job comes in that needs to use the api, and needs to make 500 requests. Since I can batch 20 items per request, it will require 25 api calls. So I would then grab 25 sets of api credentials and then invoke the Lambda function 25 times with a different set of creds for each request.

------- Original Message -------

**Comment by tusbar** [comment]
If this is the same app, the role does not change, only the refresh token changes.

**Comment by XDapps** [comment]
We're getting closer!

Looks like I just need to get the roles/permissions configured properly.

AccessDenied: User: arn:aws:sts:::assumed-role/data-sync-dev-us-east-2-lambdaRole/data-sync-dev-TestApi is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam:::role/Amazon-SP-API-Role

**Comment by tusbar** [comment]
Check the role’s trust policy, make sure it can be assumed, and make sure that your lambda’s role can `sts:AssumeRole` the role.

**Comment by XDapps** [comment]
> Check the role’s trust policy, make sure it can be assumed, and make sure that your lambda’s execution role can `sts:AssumeRole` the role.

This was the problem. Once I updated trust policy to allow sts:Assume and included the principal info it started working. 

Thank you for the guidance!

**Comment by tusbar** [comment]
Glad it helped.
