### ISSUE TITLE
Issue with Auth Types on Catalog APIs

### ISSUE THREAD

**Issue by XDapps** [bizon/selling-partner-api-sdk#906]
I have a working API using the `@sp-api-sdk/catalog-items-api-2022-04-01` package and the `@sp-api-sdk/auth`;

However, there is some data needed that is only available in the `@sp-api-sdk/catalog-items-api-2020-12-01` package.

When I try to use the `@sp-api-sdk/catalog-items-api-2020-12-01` with the  the `@sp-api-sdk/auth` package. I am getting the following error:

`/@sp-api-sdk/auth/dist/types/src/index").SellingPartnerApiAuth' is not assignable to type 

@sp-api-sdk/catalog-items-api-2020-12-01/node_modules/@sp-api-sdk/auth/dist/types/src/index").SellingPartnerApiAuth'.

 Types of property 'accessToken' are incompatible.

AccessTokenFactory' is not assignable to type 'import("/@sp-api-sdk/catalog-items-api-2020-12-01/node_modules/@sp-api-sdk/auth/dist/types/src/access-token").AccessTokenFactory'.
Types have separate declarations of a private property 'value'.ts(2322)
axios.d.ts(21, 5): The expected type comes from property 'auth' which is declared here on type 'ClientConfiguration'`

Where am I off track? It seems that I may need a different auth package/config for the 2020 API?

Any guidance is appreciated!

**Comment by tusbar** [comment]
You probably have incompatible versions and multiple versions of `@sp-api-sdk/auth` install the latest version for all packages, it‘ll fix it.

**Comment by XDapps** [comment]
Updated all versions to latest and now the 2020 Catalogs API is returning this error.

```STSServiceException [ValidationError]: 1 validation error detected: Value '[object Object]' at 'roleArn' failed to satisfy constraint: Member must have length greater than or equal to 20```

Do the credentials need to be passed differently for the 2020 Catalog Api?

**Comment by tusbar** [comment]
The error message is pretty straightforward, the role ARN you’re passing is not what you think it is.

**Comment by XDapps** [comment]
I'm an idiot...was sending a post request to a get handler...
